---
title: "COVID project- timelines of cases, deaths and vaccinations"
author: "AllanJDumont"
date: "12/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r import_format_data, echo=FALSE}
#------------EDA on the WHP covid-19 dataset-------------

#set environment, import data, join files, format data...............

library(tidyverse)
library(readxl)

# ---------------------------------------
# COVID-19 data link courtesy of  
# WHO COVID-19 Dashboard. Geneva: World Health Organization, 2020. Available online: https://covid19.who.int/ (last cited:)
print(date())
# Creative Commons Licence: CC BY-NC-SA 3.0 IGO.

global_data <- read.csv("https://covid19.who.int/WHO-COVID-19-global-data.csv", stringsAsFactors = FALSE)
str(global_data)
# ---------------------------------------

# ---------------------------------------
# UN population data courtesy of
# United Nations, Department of Economic and Social Affairs, Population Division (2019). World Population Prospects 2019, Online Edition. Rev. 1.
# Creative Commons Licence: CC BY 3.0 IGO: http://creativecommons.org/licenses/by/3.0/igo/
# download link "Total Population - Both Sexes (XLSX, 2.4 MB)"

world_population <- read_xlsx(file.choose(), sheet = "ESTIMATES")
str(world_population)
# ---------------------------------------

#transform world population data and join covid global data ..............
names(world_population)[names(world_population) %in% c("Region, subregion, country or area *", "2020")] <- c("name","population")

world_population1 <- world_population %>%
    filter(Type == "Country/Area") %>%
    select(name,population) %>%
    mutate(name = trimws(name), population=as.numeric(population)*1000)

world_population1$name[world_population1$name == "United Kingdom"] <- "The United Kingdom"

covid_file <- inner_join(
    global_data, world_population1,
    by = c("Country" = "name"),
    suffix = c(".x", ".y")
    )

library(lubridate)

#format and clean covid file  ................

clean_covid_file <- covid_file %>% 
#    mutate(Date_reported = as.POSIXct(ï..Date_reported),
    mutate(Date_reported = as.Date(ï..Date_reported),
           year = year(Date_reported),
           month = month(Date_reported),
           week = week(Date_reported),
           cases_per_capita = New_cases/population*1000000,
           deaths_per_capita = New_deaths/population*1000000) %>%
    rename(date_reported=Date_reported,
           country=Country,
           new_cases=New_cases,
           cumulative_cases=Cumulative_cases,
           new_deaths=New_deaths,
           cumulative_deaths=Cumulative_deaths,
           who_region=WHO_region) %>%
    select(year,month,week,date_reported,country,who_region,
           new_cases,cumulative_cases,new_deaths,cumulative_deaths,
           cases_per_capita,deaths_per_capita)

gc() # garbage collection

```

```{r functions_definition, echo=FALSE}

library(gridExtra)  # grid.arrange() function
library(scales)     # scales function

#parameters
selected_date <- "2021-12-01"
date_intervals <- "1 day"
selected_group1 <- factor(c("The United Kingdom", "Canada", "United States of America"),
                          levels=c("The United Kingdom", "United States of America", "Canada"))
selected_group2 <- factor(c("The United Kingdom", "Denmark", "Italy"),
                          levels=c("The United Kingdom", "Denmark", "Italy"))
                  #"Spain",
                  #"Australia"
                  #"Turkey"
region_group <- factor(c("AFRO", "AMRO", "EMRO", "EURO", "SEARO", "WPRO"),
                       levels=c("EURO", "AMRO", "AFRO", "EMRO", "SEARO", "WPRO"))

#plotting function ..................

plotting <- function(datafile, facetby, x, y, x_label, y_label, plot_heading){
    ggplot(datafile, aes(x, y, col = facetby)) +
        geom_point() +
        geom_segment(xend=x, yend=0) +
        facet_wrap(vars(facetby),labeller=as_labeller(group_names)) +
        labs(title=plot_heading, subtitle=selected_date) +
        xlab(x_label) +
        ylab(y_label) +
        theme(legend.position="none") +
        theme(axis.text.x = element_text(angle=90,vjust=0.5,size=6)) +
        scale_x_date(date_breaks=date_intervals) +
        scale_y_continuous(labels=comma)
}

```

``` {r UK_vs_North_America, echo=FALSE}
#plot execution ..........

#plot cases and deaths for countries in group 1 ...........

country_data <- clean_covid_file %>% 
    filter(date_reported >= selected_date) %>%
    filter(country %in% selected_group1) %>%
    group_by(country,date_reported) %>% 
    summarise_at(vars(cases_per_capita,deaths_per_capita),sum)
country_data$facetby <-factor(country_data$country, levels=levels(selected_group1))

group_names <- NULL
plot_cases <- plotting(country_data, country_data$facetby,country_data$date_reported, country_data$cases_per_capita, "Date Reported", "Cases/million", "Covid-19 cases per million for UK vs. North America")
plot_deaths <- plotting(country_data, country_data$facetby, country_data$date_reported, country_data$deaths_per_capita, "Date Reported", "Deaths/million", "Covid-19 deaths per million for UK vs.North America")
UK_vs_North_America <- grid.arrange(plot_cases,plot_deaths,nrow=2)

```

``` {r UK_vs_Europe, echo=FALSE}

#plot cases and deaths for countries in group 2 ...........

country_data <- clean_covid_file %>% 
    filter(date_reported >= selected_date) %>%
    filter(country %in% selected_group2) %>%
    group_by(country,date_reported) %>% 
    summarise_at(vars(cases_per_capita, deaths_per_capita),sum)
country_data$facetby <-factor(country_data$country, levels=levels(selected_group2))

plot_cases <- plotting(country_data, country_data$facetby, country_data$date_reported, country_data$cases_per_capita, "Date Reported", "Cases/million", "Covid-19 cases per million for UK vs. Europe")
plot_deaths <- plotting(country_data, country_data$facetby, country_data$date_reported, country_data$deaths_per_capita, "Date Reported", "Deaths/million", "Covid-19 deaths per million for UK vs. Europe")
UK_vs_Europe <- grid.arrange(plot_cases,plot_deaths,nrow=2)

```

``` {r worldwide_by_region, echo=FALSE}
#plot cases and deaths worldwide by region .................

region_data <- clean_covid_file %>% 
    filter(date_reported >= selected_date) %>%
    filter(who_region !="Other") %>%
    group_by(who_region,date_reported) %>% 
    summarise_at(vars(cases_per_capita,deaths_per_capita),sum)
region_data$facetby <- factor(region_data$who_region, levels=levels(region_group))

group_names <- c("AFRO" = "Africa",
                 "AMRO" = "Americas",
                 "EMRO" = "Eastern Mediterrean",
                 "EURO" = "Europe",
                 "SEARO" = "South-East Asia",
                 "WPRO" = "Western Pacific")
plot_cases <- plotting(region_data, region_data$facetby,region_data$date_reported, region_data$cases_per_capita, "Date Reported", "Cases/million", "Covid-19 Cases per million worldwide")
plot_deaths <- plotting(region_data, region_data$facetby,region_data$date_reported, region_data$deaths_per_capita, "Date Reported", "Deaths/million", "Covid-19 Deaths per million worldwide")
worldwide_by_region <- grid.arrange(plot_cases, plot_deaths, nrow=2)

```

